### ISSUE TITLE
Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by krthr** [krthr/linku2.0-api#11]
```js
TypeError: Cannot read property 'toUpperCase' of undefined
    at firstname.trim.split.map (/usr/src/app/src/services/scraper.js:162:31)
    at Array.map (<anonymous>)
    at Promise.all.$.html.match.slice.map.elem (/usr/src/app/src/services/scraper.js:161:12)
    at Array.map (<anonymous>)
    at getGroupByNRC (/usr/src/app/src/services/scraper.js:152:8)
    at process._tickCallback (internal/process/next_tick.js:68:7)TypeError: Cannot read property 'toUpperCase' of undefined
    at firstname.trim.split.map (/usr/src/app/src/services/scraper.js:162:31)
    at Array.map (<anonymous>)
    at Promise.all.$.html.match.slice.map.elem (/usr/src/app/src/services/scraper.js:161:12)
    at Array.map (<anonymous>)
    at getGroupByNRC (/usr/src/app/src/services/scraper.js:152:8)
    at process._tickCallback (internal/process/next_tick.js:68:7)TypeError: Cannot read property 'toUpperCase' of undefined
    at firstname.trim.split.map (/usr/src/app/src/services/scraper.js:162:31)
    at Array.map (<anonymous>)
    at Promise.all.$.html.match.slice.map.elem (/usr/src/app/src/services/scraper.js:161:12)
    at Array.map (<anonymous>)
    at getGroupByNRC (/usr/src/app/src/services/scraper.js:152:8)
    at process._tickCallback (internal/process/next_tick.js:68:7)TypeError: Cannot read property 'toUpperCase' of undefined
    at firstname.trim.split.map (/usr/src/app/src/services/scraper.js:162:31)
    at Array.map (<anonymous>)
    at Promise.all.$.html.match.slice.map.elem (/usr/src/app/src/services/scraper.js:161:12)
    at Array.map (<anonymous>)
    at getGroupByNRC (/usr/src/app/src/services/scraper.js:152:8)
    at process._tickCallback (internal/process/next_tick.js:68:7)TypeError: Cannot read property 'toUpperCase' of undefined
    at firstname.trim.split.map (/usr/src/app/src/services/scraper.js:162:31)
    at Array.map (<anonymous>)
    at Promise.all.$.html.match.slice.map.elem (/usr/src/app/src/services/scraper.js:161:12)
    at Array.map (<anonymous>)
    at getGroupByNRC (/usr/src/app/src/services/scraper.js:152:8)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by krthr** [comment]
This error happened when the scraping jobs were running.
